I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapitres/0-naissance.rpy", line 3, in script
    init -5 python:
  File "game/chapitres/0-naissance.rpy", line 3, in script
    init -5 python:
  File "game/chapitres/0-naissance.rpy", line 19, in <module>
    from spe.univers.coteries import templiers
ImportError: No module named extremis.geographie

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/chapitres/0-naissance.rpy", line 3, in script
    init -5 python:
  File "game/chapitres/0-naissance.rpy", line 3, in script
    init -5 python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/chapitres/0-naissance.rpy", line 19, in <module>
    from spe.univers.coteries import templiers
  File "renpy/loader.py", line 985, in load_module
    exec(code, mod.__dict__)
  File "spe/univers/coteries/templiers.py", line 4, in <module>
ImportError: No module named extremis.geographie

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
extremisLaVille 1.0
Tue May 24 20:39:39 2022
